baseURL = "https://stockfish-ooo.github.io/"
languageCode = "zh-cn"
title = "Zhuocheng Zhu"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  math = true
  comments = true
  socialIcons = [
    {name = "github", url = "https://github.com/stockfish-ooo"},
    {name = "zhihu", url = "https://www.zhihu.com/people/123456-81-42-65"},
    {name = "xiaohongshu", url = "https://www.xiaohongshu.com/user/profile/6045dbd40000000001000184"},
  ]

[params.homeInfoParams]
  Title = "Zhuocheng Zhu"
  Content = "Biomedical Engineering / Applied Mathematics\nPersonal academic notes & learning archive\n"
  imageUrl = "/images/25-12-boya-tower.jpg"
  imageWidth = 140
  imageHeight = 140

[menu]

  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Websites"
    url = "/websites/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
