baseURL = "https://stockfish-ooo.github.io/"
languageCode = "zh-cn"
title = "Zhuocheng Zhu"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  math = true
  socialIcons = [
    {name = "github", url = "https://github.com/stockfish-ooo"},
    {name = "zhihu", url = "https://www.zhihu.com/people/123456-81-42-65"}
  ]

[params.homeInfoParams]
  Title = "Zhuocheng Zhu"
  Content = """
Biomedical Engineering / Applied Mathematics  
Personal academic notes & learning archive
"""

[menu]

  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true